name: Install libncurses5

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update package index
        run: sudo apt-get update

      - name: Install libncurses5
        run: sudo apt-get install -y libncurses5
