name: Build APK

on:
  push:
    branches:
      - main  # Exécute le processus lors des commits dans la branche 'main'

jobs:
  build:
    runs-on: ubuntu-20.04  # Tu peux aussi essayer d'utiliser ubuntu-22.04 si nécessaire

    steps:
      # Étape 1: Checkout du repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2: Installation de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8  # Spécifie la version de Python à utiliser

      # Étape 3: Installation des dépendances
      - name: Install dependencies
        run: |
          # Mise à jour des informations des paquets
          sudo apt update
          
          # Installation des paquets nécessaires (seulement 64 bits)
          sudo apt install -y \
            libncurses6 \
            libncurses-dev \
            libreadline-dev \
            libffi-dev \
            libssl-dev \
            autoconf \
            libtool \
            pkg-config \
            zip \
            unzip \
            python3-pip \
            cmake \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev
        shell: bash

      # Étape 4: Installation des packages .deb locaux
      - name: Install local .deb packages
        run: |
          # Installation des fichiers .deb locaux
          sudo dpkg -i lib64tinfo6_6.5+20250216-2_amd64.deb || sudo apt-get install -f -y
        shell: bash

      # Étape 5: Installation des dépendances pour Buildozer
      - name: Install Buildozer dependencies
        run: |
          python3 -m pip install --upgrade Cython==0.29.33 buildozer
        shell: bash

      # Étape 6: Installation de Gradle version 7.6
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          sudo mkdir /opt/gradle
          sudo unzip -d /opt/gradle gradle-7.6-bin.zip
          echo "export PATH=/opt/gradle/gradle-7.6/bin:$PATH" >> $HOME/.bashrc
          echo "export PATH=/opt/gradle/gradle-7.6/bin:$PATH" >> $HOME/.profile
          export PATH=/opt/gradle/gradle-7.6/bin:$PATH
          gradle -v  # Vérification de l'installation
        shell: bash

      # Étape 7: Compilation de l'APK avec Buildozer (mode verbose activé)
      - name: Build APK with Buildozer
        run: |
          buildozer android debug 
        shell: bash

      # Étape 8: Téléversement de l'APK généré en tant qu'artefact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package  # Nom de l'artefact
          path: ./bin/*.apk  # Chemin vers l'APK généré
