name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04  # Utilisation d'Ubuntu 20.04 pour plus de compatibilité

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe  # Ajoute le dépôt 'universe'
          sudo apt update  # Met à jour les listes après avoir ajouté le dépôt
          sudo apt install -y \
            libncurses5 \
            libncurses5:i386 \  # Installe les versions 32 bits de libncurses si nécessaire
            libreadline-dev \
            libffi-dev \
            libssl-dev \
            autoconf \
            libtool \
            pkg-config \
            zip \
            unzip \
            python3-pip \
            cmake \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev
        shell: bash

      - name: Install Buildozer dependencies
        run: |
          python3 -m pip install --upgrade Cython==0.29.33 buildozer
        shell: bash

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug
        shell: bash

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
